import unittest
from datetime import datetime

from itrader.portfolio_handler.transaction import Transaction, TransactionType
from itrader.portfolio_handler.position import Position, PositionSide


class TestPosition(unittest.TestCase):
	"""
	Test a Position generated by a transaction being processed
	by the portfolio.
	"""

	@classmethod
	def setUpClass(cls):
		"""
		Set up the test data that will be used across all test methods.
		"""
		cls.ticker = 'BTCUSDT'
		cls.strategy_id = 'test_strategy'
		cls.portfolio_id = 'portfolio_id'

	def test_open_long_position(self):
		time = datetime.now()
		type = TransactionType.BUY
		price = 42000
		quantity = 1
		commission = 0
		buy_transaction = Transaction(time, type, self.ticker, 'side', 
								price, quantity, commission,
								self.portfolio_id)
		position = Position.open_position(buy_transaction)

		self.assertIsInstance(position, Position)
		self.assertEqual(position.id, 1)
		self.assertEqual(position.ticker, 'BTCUSDT')
		self.assertEqual(position.portfolio_id, 'portfolio_id')

		self.assertEqual(position.is_open, True)
		self.assertEqual(position.side, PositionSide.LONG)
		self.assertEqual(position.buy_quantity, 1)
		self.assertEqual(position.sell_quantity, 0)
		self.assertEqual(position.avg_bought, 42000)
		self.assertEqual(position.avg_sold, 0)
		self.assertEqual(position.avg_price, 42000)
		self.assertEqual(position.market_value, 42000)
		self.assertEqual(position.total_bought, 42000)
		self.assertEqual(position.total_sold, 0)
		self.assertEqual(position.net_total, 0)
		self.assertEqual(position.realised_pnl, 0)
		self.assertEqual(position.unrealised_pnl, 0)

	def test_open_short_position(self):
		time = datetime.now()
		type = TransactionType.SELL
		price = 42000
		quantity = 1
		commission = 0
		sell_transaction = Transaction(time, type, self.ticker, 'side', 
								price, quantity, commission,
								self.portfolio_id)
		position = Position.open_position(sell_transaction)

		self.assertIsInstance(position, Position)
		self.assertEqual(position.id, 2)
		self.assertEqual(position.ticker, 'BTCUSDT')
		self.assertEqual(position.portfolio_id, 'portfolio_id')

		self.assertEqual(position.is_open, True)
		self.assertEqual(position.side, PositionSide.SHORT)
		self.assertEqual(position.buy_quantity, 0)
		self.assertEqual(position.sell_quantity, 1)
		self.assertEqual(position.avg_bought, 0)
		self.assertEqual(position.avg_sold, 42000)
		self.assertEqual(position.avg_price, 42000)
		self.assertEqual(position.total_bought, 0)
		self.assertEqual(position.total_sold, 42000)
		self.assertEqual(position.net_total, 0)
		self.assertEqual(position.realised_pnl, 0)
		self.assertEqual(position.unrealised_pnl, 0)

	def test_update_price_time_long_position(self):
		time = datetime.now()
		type = TransactionType.BUY
		price = 42000
		quantity = 1
		commission = 0
		buy_transaction = Transaction(time, type, self.ticker, 'side', 
								price, quantity, commission,
								self.portfolio_id)
		position = Position.open_position(buy_transaction)
		# Update price and time
		time = datetime.now()
		position.update_current_price_time(50000, time)

		self.assertIsInstance(position, Position)
		self.assertEqual(position.id, 3)
		self.assertEqual(position.ticker, 'BTCUSDT')
		self.assertEqual(position.portfolio_id, 'portfolio_id')

		self.assertEqual(position.is_open, True)
		self.assertEqual(position.side, PositionSide.LONG)
		self.assertEqual(position.buy_quantity, 1)
		self.assertEqual(position.sell_quantity, 0)
		self.assertEqual(position.avg_bought, 42000)
		self.assertEqual(position.avg_sold, 0)
		self.assertEqual(position.avg_price, 42000)
		self.assertEqual(position.market_value, 50000)
		self.assertEqual(position.total_bought, 42000)
		self.assertEqual(position.total_sold, 0)
		self.assertEqual(position.net_total, 8000)
		self.assertEqual(position.realised_pnl, 0)
		self.assertEqual(position.unrealised_pnl, 8000)
	
	def test_update_price_time_short_position(self):
		time = datetime.now()
		type = TransactionType.SELL
		price = 42000
		quantity = 1
		commission = 0
		sell_transaction = Transaction(time, type, self.ticker, 'side', 
								price, quantity, commission,
								self.portfolio_id)
		position = Position.open_position(sell_transaction)
		# Update price and time
		time = datetime.now()
		position.update_current_price_time(50000, time)

		self.assertIsInstance(position, Position)
		self.assertEqual(position.id, 4)
		self.assertEqual(position.ticker, 'BTCUSDT')
		self.assertEqual(position.portfolio_id, 'portfolio_id')

		self.assertEqual(position.is_open, True)
		self.assertEqual(position.side, PositionSide.SHORT)
		self.assertEqual(position.buy_quantity, 0)
		self.assertEqual(position.sell_quantity, 1)
		self.assertEqual(position.avg_bought, 0)
		self.assertEqual(position.avg_sold, 42000)
		self.assertEqual(position.avg_price, 42000)
		self.assertEqual(position.market_value, 50000)
		self.assertEqual(position.total_bought, 0)
		self.assertEqual(position.total_sold, 42000)
		self.assertEqual(position.net_total, -8000)
		self.assertEqual(position.realised_pnl, 0)
		self.assertEqual(position.unrealised_pnl, -8000)

if __name__ == "__main__":
	unittest.main()