"""
Fill event: the exchange's immutable execution truth, construct-complete
(D-12 — executed values are constructor inputs, never post-mutations).
"""

import uuid
from dataclasses import dataclass, field
from datetime import datetime
from decimal import Decimal

import uuid_utils.compat as uuid_compat

from itrader.core.enums import EventType, FillStatus, Side
from itrader.core.ids import OrderId, PortfolioId, StrategyId
from itrader.core.money import to_money

from .base import Event
from .order import OrderEvent


@dataclass(frozen=True, slots=True, kw_only=True)
class FillEvent(Event):
    """
    This event is generated by the ExecutionHandler in response to
    an executed order.
    Stores the price and quantity and commission confirmed by
    the exchange.

    Parameters
    ----------
    time: `timestamp`
        Event time
    ticker: `str`
        The ticker symbol, e.g. 'BTCUSD'.
    action: `Side`
        ``Side.BUY`` (for long) or ``Side.SELL`` (for short)
    quantity: `Decimal`
        Quantity transacted (Decimal since D-22, closing the Phase 4 D-04
        deferral — float inputs enter via ``to_money`` at construction)
    price: `Decimal`
        Executed price confirmed by the exchange (Decimal, D-22)
    commission: `Decimal`
        Transaction fee (Decimal, D-22)
    portfolio_id: `PortfolioId`
        UUIDv7-backed portfolio identity where transact the position
    fill_id: `uuid.UUID`
        REQUIRED — unique UUIDv7 identity of this fill, generated by the
        exchange at fill construction (D-12).
    order_id: `OrderId`
        REQUIRED — id of the originating order, carried for mirror
        reconciliation (D-12 fill -> order -> strategy audit chain).
    strategy_id: `StrategyId`
        The originating strategy, carried from the order for the full
        fill -> order -> strategy audit chain (D-12).
    """

    type: EventType = field(default=EventType.FILL, init=False)
    status: FillStatus
    ticker: str
    action: Side
    price: Decimal
    quantity: Decimal
    commission: Decimal
    # FL-02: portfolio_id carries a UUIDv7-backed PortfolioId (#10 carry-forward).
    portfolio_id: PortfolioId
    fill_id: uuid.UUID
    order_id: OrderId
    strategy_id: StrategyId
    # LEV-03 (Finding B): the admission-clamped EFFECTIVE leverage carried from
    # the originating order. Default Decimal("1") is unlevered (oracle-dark);
    # EXECUTED and REFUSED/CANCELLED fills all carry it for the Transaction hop.
    leverage: Decimal = Decimal("1")

    def __str__(self) -> str:
        return f'{self.type} ({self.ticker}, {self.action}, {round(self.quantity, 4)}, {round(self.price, 4)} $)'

    def __repr__(self) -> str:
        return str(self)

    @classmethod
    def new_fill(cls, status: str, order: OrderEvent, *,
                 price: 'Decimal | float', quantity: 'Decimal | float',
                 commission: 'Decimal | float',
                 time: 'datetime | None' = None) -> 'FillEvent':
        """
        Generate a complete FillEvent from the originating order.

        Construct-complete (D-12): the exchange passes the executed values
        explicitly as keyword-only arguments — a FillEvent is never mutated
        after construction (the dataclass is frozen). ``fill_id`` is a
        fresh UUIDv7 generated here, at fill construction; ``strategy_id``
        and ``order_id`` are carried from the originating order for the
        fill -> order -> strategy audit chain. REFUSED/CANCELLED fills
        pass the order's own price/quantity with commission Decimal("0").

        Fill time (D-01/D-13): for outcomes produced by a market-data bar
        (EXECUTED matches, OCO CANCELLED) the exchange passes the MATCHING
        BAR's event time — an order decided at tick T fills with
        FillEvent.time = T+1tf, never the decision tick. When ``time`` is
        omitted the fill defaults to the order's own decision time, which
        is correct for admission-time outcomes (REFUSED rejections, CANCEL
        command acknowledgements).

        Money (D-22): this is THE float -> Decimal crossing for execution
        output. Float values from the exchange's internal matching/slippage
        math enter the money domain here, once, via ``to_money``
        (``Decimal(str(x))`` — numerically inert by construction, D-04);
        Decimal inputs pass through as an identity normalization.

        Parameters
        ----------
        status : `str`
            The execution state of the fill order e.g. 'EXECUTED', 'REFUSED', 'CANCELLED'
        order : `OrderEvent`
            The instance of the originating order
        price : `Decimal | float`
            Executed price confirmed by the exchange (keyword-only)
        quantity : `Decimal | float`
            Executed quantity confirmed by the exchange (keyword-only)
        commission : `Decimal | float`
            Transaction fee charged by the exchange (keyword-only)
        time : `datetime`, optional
            The fill's event time — the matching bar's time for fills
            decided by a bar (D-01/D-13). Defaults to the order's
            decision time for admission-time outcomes.

        Returns
        -------
        fill : `FillEvent`
            Complete fill — no field is rewritten after this returns
        """

        fill_status = FillStatus(status)
        return cls(
            time=time if time is not None else order.time,
            status=fill_status,
            ticker=order.ticker,
            action=order.action,
            price=to_money(price),
            quantity=to_money(quantity),
            commission=to_money(commission),
            portfolio_id=order.portfolio_id,
            fill_id=uuid_compat.uuid7(),
            order_id=order.order_id,
            strategy_id=order.strategy_id,
            # LEV-03 (Finding B): carry the effective leverage from the order.
            # getattr default keeps hand-built order stubs (predating the field)
            # working — they degrade to Decimal("1") (oracle-dark).
            leverage=getattr(order, "leverage", Decimal("1")),
        )
