"""
Fill event: the exchange's immutable execution truth, construct-complete
(D-12 — executed values are constructor inputs, never post-mutations).
"""

import uuid
from dataclasses import dataclass, field

import uuid_utils.compat as uuid_compat

from itrader.core.enums import EventType, FillStatus, Side
from itrader.core.ids import OrderId, StrategyId

from .base import Event
from .order import OrderEvent


@dataclass(frozen=True, slots=True, kw_only=True)
class FillEvent(Event):
    """
    This event is generated by the ExecutionHandler in response to
    an executed order.
    Stores the price and quantity and commission confirmed by
    the exchange.

    Parameters
    ----------
    time: `timestamp`
        Event time
    ticker: `str`
        The ticker symbol, e.g. 'BTCUSD'.
    action: `Side`
        ``Side.BUY`` (for long) or ``Side.SELL`` (for short)
    quantity: `float`
        Quantity transacted
    price: `float`
        Executed price confirmed by the exchange
    commission: `float`
        Transaction fee
    portfolio_id: `int`
        Portfolio id where transact the position
    fill_id: `uuid.UUID`
        REQUIRED — unique UUIDv7 identity of this fill, generated by the
        exchange at fill construction (D-12).
    order_id: `OrderId`
        REQUIRED — id of the originating order, carried for mirror
        reconciliation (D-12 fill -> order -> strategy audit chain).
    strategy_id: `StrategyId`
        The originating strategy, carried from the order for the full
        fill -> order -> strategy audit chain (D-12).
    """

    type: EventType = field(default=EventType.FILL, init=False)
    status: FillStatus
    ticker: str
    action: Side
    price: float
    quantity: float
    commission: float
    portfolio_id: int
    fill_id: uuid.UUID
    order_id: OrderId
    strategy_id: StrategyId

    def __str__(self) -> str:
        return f'{self.type} ({self.ticker}, {self.action}, {round(self.quantity, 4)}, {round(self.price, 4)} $)'

    def __repr__(self) -> str:
        return str(self)

    @classmethod
    def new_fill(cls, status: str, order: OrderEvent, *,
                 price: float, quantity: float, commission: float) -> 'FillEvent':
        """
        Generate a complete FillEvent from the originating order.

        Construct-complete (D-12): the exchange passes the executed values
        explicitly as keyword-only arguments — a FillEvent is never mutated
        after construction (the dataclass is frozen). ``fill_id`` is a
        fresh UUIDv7 generated here, at fill construction; ``strategy_id``
        and ``order_id`` are carried from the originating order for the
        fill -> order -> strategy audit chain. REFUSED/CANCELLED fills
        pass the order's own price/quantity with commission 0.0.

        Parameters
        ----------
        status : `str`
            The execution state of the fill order e.g. 'EXECUTED', 'REFUSED', 'CANCELLED'
        order : `OrderEvent`
            The instance of the originating order
        price : `float`
            Executed price confirmed by the exchange (keyword-only)
        quantity : `float`
            Executed quantity confirmed by the exchange (keyword-only)
        commission : `float`
            Transaction fee charged by the exchange (keyword-only)

        Returns
        -------
        fill : `FillEvent`
            Complete fill — no field is rewritten after this returns
        """

        fill_status = FillStatus(status)
        return cls(
            time=order.time,
            status=fill_status,
            ticker=order.ticker,
            action=order.action,
            price=price,
            quantity=quantity,
            commission=commission,
            portfolio_id=order.portfolio_id,
            fill_id=uuid_compat.uuid7(),
            order_id=order.order_id,
            strategy_id=order.strategy_id,
        )
