"""
Market-side events: clock ticks, bars, portfolio snapshots and screener
results. All frozen ``Event`` subclasses (M3-01).
"""

from dataclasses import dataclass, field
from typing import Any

from itrader.core.bar import Bar
from itrader.core.enums import EventType

from .base import Event


@dataclass(frozen=True, slots=True, kw_only=True)
class TimeEvent(Event):
    """
    Signals that the simulation clock advanced to ``time`` ("the clock
    advanced to T"), pairing with the ``itrader.core.clock.Clock`` family
    (D-08). Drives per-tick screening and bar generation.
    """

    type: EventType = field(default=EventType.TIME, init=False)

    def __str__(self) -> str:
        return f"{self.type}, Time: {self.time}"

    def __repr__(self) -> str:
        return str(self)


@dataclass(frozen=True, slots=True, kw_only=True)
class BarEvent(Event):
    """
    A new market OHLCV bar for every ticker that traded at ``time``.

    Payload contract (M5-02, D-14/D-15):

    - ``bars`` maps ticker -> ONE immutable ``Bar`` struct per tick
      (Decimal OHLCV entered via the string path — no pandas payloads
      on the queue).
    - A ticker with no bar at T is ABSENT from the dict (sparse
      universe / data gap); consumers guard membership with
      ``bars.get(ticker)`` or an ``in`` check.
    - The event carries only the current fact; history comes from the
      Feed (D-15 "event = fact, feed = query").
    """

    type: EventType = field(default=EventType.BAR, init=False)
    bars: dict[str, Bar]

    def __str__(self) -> str:
        return f"{self.type}, Time: {self.time}"

    def __repr__(self) -> str:
        return str(self)


@dataclass(frozen=True, slots=True, kw_only=True)
class PortfolioUpdateEvent(Event):
    """
    Periodic snapshot of all portfolios' state, generated by the
    PortfolioHandler. ``portfolios`` keeps its current documented dict
    shape (D-07 — no new DTOs this phase).
    """

    type: EventType = field(default=EventType.UPDATE, init=False)
    portfolios: dict[str, Any]

    def __str__(self) -> str:
        return f"{self.type}, Time: {self.time}"

    def __repr__(self) -> str:
        return str(self)


@dataclass(frozen=True, slots=True, kw_only=True)
class ScreenerEvent(Event):
    """
    Screener event generated from a Screener object.
    This is received by the Strategy handler object
    that update the symbol to trade of the subscribed
    strategies.

    Current fields kept unchanged (frozen structurally; D-screener owns
    the semantics).
    """

    type: EventType = field(default=EventType.SCREENER, init=False)
    screener_id: str
    screener_name: str
    subscribed_strategies: list[str]
    tickers: list[str]

    def __str__(self) -> str:
        return f"{self.type} ({self.screener_name})"

    def __repr__(self) -> str:
        return str(self)
