"""
Market-side events: clock ticks, bars, portfolio snapshots and screener
results. All frozen ``Event`` subclasses (M3-01).
"""

from dataclasses import dataclass, field
from typing import Any, Optional

import pandas as pd

from itrader.core.enums import EventType

from .base import Event


@dataclass(frozen=True, slots=True, kw_only=True)
class TimeEvent(Event):
    """
    Signals that the simulation clock advanced to ``time`` ("the clock
    advanced to T"), pairing with the ``itrader.core.clock.Clock`` family
    (D-08). Drives per-tick screening and bar generation.
    """

    type: EventType = field(default=EventType.TIME, init=False)

    def __str__(self) -> str:
        return f"{self.type}, Time: {self.time}"

    def __repr__(self) -> str:
        return str(self)


@dataclass(frozen=True, slots=True, kw_only=True)
class BarEvent(Event):
    """
    Handles the event of receiving a new market
    open-high-low-close-volume bar, as would be generated
    via common data providers.

    The ``bars`` dict payload and the ``get_last_*`` accessors are kept
    verbatim from the legacy event — M5a owns the Bar-struct redesign.
    """

    type: EventType = field(default=EventType.BAR, init=False)
    bars: dict[str, pd.DataFrame]
    # TODO:
    # improvment idea : define a Bar object instead of using a DataFrame
    # to store the bar data
    # e.g. Bar(open, high, low, close, volume)
    # where Bar is a dataclass with the above fields

    def __str__(self) -> str:
        return f"{self.type}, Time: {self.time}"

    def __repr__(self) -> str:
        return str(self)

    def get_last_close(self, ticker: str) -> float:
        close_data = self.bars[ticker]['close']

        # TODO: check why the close data is not always a Series (from test).
        # This shouldn't be the case after the before mentioned improvement is done.

        # Handle pandas Series or DataFrame column
        if hasattr(close_data, 'iloc'):
            return float(close_data.iloc[-1])
        # Handle numpy arrays
        elif hasattr(close_data, '__getitem__') and hasattr(close_data, '__len__'):
            return float(close_data[-1])
        # Handle scalar values
        else:
            return float(close_data)

    def get_last_open(self, ticker: str) -> Optional[float]:
        """
        Get the opening price for the ticker from the current bar.

        Parameters
        ----------
        ticker : str
            The ticker symbol

        Returns
        -------
        float
            The opening price for the ticker
        """
        if ticker not in self.bars:
            return None

        open_data = self.bars[ticker]['open']

        # Handle pandas Series or DataFrame column
        if hasattr(open_data, 'iloc'):
            return float(open_data.iloc[-1])
        # Handle numpy arrays
        elif hasattr(open_data, '__getitem__') and hasattr(open_data, '__len__'):
            return float(open_data[-1])
        # Handle scalar values
        else:
            return float(open_data)

    def get_last_high(self, ticker: str) -> Optional[float]:
        """
        Get the high price for the ticker from the current bar.

        Parameters
        ----------
        ticker : str
            The ticker symbol

        Returns
        -------
        float
            The high price for the ticker
        """
        if ticker not in self.bars:
            return None

        high_data = self.bars[ticker]['high']

        # Handle pandas Series or DataFrame column
        if hasattr(high_data, 'iloc'):
            return float(high_data.iloc[-1])
        # Handle numpy arrays
        elif hasattr(high_data, '__getitem__') and hasattr(high_data, '__len__'):
            return float(high_data[-1])
        # Handle scalar values
        else:
            return float(high_data)

    def get_last_low(self, ticker: str) -> Optional[float]:
        """
        Get the low price for the ticker from the current bar.

        Parameters
        ----------
        ticker : str
            The ticker symbol

        Returns
        -------
        float
            The low price for the ticker
        """
        if ticker not in self.bars:
            return None

        low_data = self.bars[ticker]['low']

        # Handle pandas Series or DataFrame column
        if hasattr(low_data, 'iloc'):
            return float(low_data.iloc[-1])
        # Handle numpy arrays
        elif hasattr(low_data, '__getitem__') and hasattr(low_data, '__len__'):
            return float(low_data[-1])
        # Handle scalar values
        else:
            return float(low_data)


@dataclass(frozen=True, slots=True, kw_only=True)
class PortfolioUpdateEvent(Event):
    """
    Periodic snapshot of all portfolios' state, generated by the
    PortfolioHandler. ``portfolios`` keeps its current documented dict
    shape (D-07 — no new DTOs this phase).
    """

    type: EventType = field(default=EventType.UPDATE, init=False)
    portfolios: dict[str, Any]

    def __str__(self) -> str:
        return f"{self.type}, Time: {self.time}"

    def __repr__(self) -> str:
        return str(self)


@dataclass(frozen=True, slots=True, kw_only=True)
class ScreenerEvent(Event):
    """
    Screener event generated from a Screener object.
    This is received by the Strategy handler object
    that update the symbol to trade of the subscribed
    strategies.

    Current fields kept unchanged (frozen structurally; D-screener owns
    the semantics).
    """

    type: EventType = field(default=EventType.SCREENER, init=False)
    screener_id: str
    screener_name: str
    subscribed_strategies: list[str]
    tickers: list[str]

    def __str__(self) -> str:
        return f"{self.type} ({self.screener_name})"

    def __repr__(self) -> str:
        return str(self)
