"""
Order event: the immutable instruction sent to the execution layer,
fully linked to its originating Order entity (D-11/D-12).
"""

from dataclasses import dataclass, field
from decimal import Decimal
from typing import Any

from itrader.core.enums import EventType, OrderCommand, OrderType, Side
from itrader.core.ids import OrderId, StrategyId

from .base import Event


@dataclass(frozen=True, slots=True, kw_only=True)
class OrderEvent(Event):
    """
    An OrderEvent is generated by the OrderHandler in response to
    a signal event which has been validated against the Order entity
    (D-13). It is then sent to the ExecutionHandler who sends the order
    to the exchange.

    Linkage (D-11/D-12): ``order_id`` is REQUIRED — every order event
    traces to its Order entity. A bracket parent carries its children's
    ids in ``child_order_ids``; non-bracket orders carry the empty tuple.

    Money (D-22, closing the Phase 4 D-04 deferral): ``price``/``quantity``/
    ``stop_price`` are Decimal — the entity's Decimal money passes through
    the event untouched. The execution layer converts ONCE at its float
    matching/slippage boundary and re-enters Decimal via ``to_money`` at
    FillEvent construction.
    """

    type: EventType = field(default=EventType.ORDER, init=False)
    ticker: str
    action: Side
    price: Decimal
    quantity: Decimal
    exchange: str
    strategy_id: StrategyId
    portfolio_id: int
    order_type: OrderType
    # D-12: required linkage — ids are UUIDv7-backed since M2; an OrderEvent
    # without its entity id is malformed by construction (TypeError).
    order_id: OrderId
    stop_price: Decimal | None = None
    parent_order_id: OrderId | None = None
    # D-11: two-directional bracket linkage — a bracket parent carries its
    # children's ids; non-bracket orders carry the empty tuple.
    child_order_ids: tuple[OrderId, ...] = ()
    command: OrderCommand = OrderCommand.NEW

    def __str__(self) -> str:
        base = f"{self.type} ({self.ticker}, {self.action}, {self.order_type.name}, {self.quantity}, {round(self.price, 4)} $"
        if self.stop_price:
            base += f", stop: {round(self.stop_price, 4)}"
        return base + f", ID: {self.order_id})"

    def __repr__(self) -> str:
        return str(self)

    @classmethod
    def new_order_event(cls, order: Any, command: OrderCommand = OrderCommand.NEW) -> 'OrderEvent':
        """
        Generate a new OrderEvent from an Order entity.

        Reads the order's real type (``order.type``) and id (``order.id``
        — required, no getattr-None default, D-12), plus the bracket
        linkage (``parent_order_id`` / ``child_order_ids``, D-11) and the
        command intent.

        Money (D-22): the entity's Decimal ``price``/``quantity`` pass
        through EXACTLY — the former M2a float() boundary coercion is gone.
        """
        return cls(
            time=order.time,
            ticker=order.ticker,
            action=Side(order.action),
            price=order.price,
            quantity=order.quantity,
            exchange=order.exchange,
            strategy_id=order.strategy_id,
            portfolio_id=order.portfolio_id,
            order_type=order.type,
            # The Order entity carries no stop_price field today — preserve the
            # legacy getattr-None read until the entity grows one.
            stop_price=getattr(order, 'stop_price', None),
            order_id=order.id,
            parent_order_id=order.parent_order_id,
            child_order_ids=tuple(order.child_order_ids),
            command=command,
        )
