"""operational baseline

Revision ID: 2cbf0bf6b0b6
Revises: 
Create Date: 2026-06-29 18:14:10.643416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# Autogenerate renders the custom money/time TypeDecorator by its fully-qualified name
# (``itrader.storage.types.UtcIsoText``) but does NOT emit the import — the standard
# custom-type autogenerate gotcha. Added by hand-review so ``alembic upgrade head`` resolves
# the name instead of raising ``NameError`` (Pitfall 5 / D-09 hand-review).
import itrader.storage.types

# revision identifiers, used by Alembic.
revision: str = '2cbf0bf6b0b6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cash_operations',
    sa.Column('operation_id', sa.Uuid(), nullable=False),
    sa.Column('portfolio_id', sa.Uuid(), nullable=False),
    sa.Column('operation_type', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(), nullable=False),
    sa.Column('timestamp', itrader.storage.types.UtcIsoText(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('fee', sa.Numeric(), nullable=False),
    sa.Column('reference_id', sa.String(), nullable=True),
    sa.Column('balance_before', sa.Numeric(), nullable=True),
    sa.Column('balance_after', sa.Numeric(), nullable=True),
    sa.PrimaryKeyConstraint('operation_id', name=op.f('pk_cash_operations'))
    )
    with op.batch_alter_table('cash_operations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cash_operations_portfolio_id'), ['portfolio_id'], unique=False)

    op.create_table('cash_reservations',
    sa.Column('portfolio_id', sa.Uuid(), nullable=False),
    sa.Column('reference_id', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(), nullable=False),
    sa.PrimaryKeyConstraint('portfolio_id', 'reference_id', name=op.f('pk_cash_reservations'))
    )
    op.create_table('equity_snapshots',
    sa.Column('portfolio_id', sa.Uuid(), nullable=False),
    sa.Column('seq', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('timestamp', itrader.storage.types.UtcIsoText(), nullable=False),
    sa.Column('total_equity', sa.Numeric(), nullable=False),
    sa.Column('cash_balance', sa.Numeric(), nullable=False),
    sa.Column('positions_value', sa.Numeric(), nullable=False),
    sa.Column('unrealized_pnl', sa.Numeric(), nullable=False),
    sa.Column('realized_pnl', sa.Numeric(), nullable=False),
    sa.Column('total_pnl', sa.Numeric(), nullable=False),
    sa.Column('open_positions_count', sa.Integer(), nullable=False),
    sa.Column('portfolio_return', sa.Numeric(), nullable=False),
    sa.Column('benchmark_return', sa.Numeric(), nullable=True),
    sa.PrimaryKeyConstraint('portfolio_id', 'seq', name=op.f('pk_equity_snapshots'))
    )
    op.create_table('locked_margin',
    sa.Column('portfolio_id', sa.Uuid(), nullable=False),
    sa.Column('position_id', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(), nullable=False),
    sa.PrimaryKeyConstraint('portfolio_id', 'position_id', name=op.f('pk_locked_margin'))
    )
    op.create_table('orders',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('time', itrader.storage.types.UtcIsoText(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('ticker', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('price', sa.Numeric(), nullable=True),
    sa.Column('quantity', sa.Numeric(), nullable=True),
    sa.Column('exchange', sa.String(), nullable=True),
    sa.Column('strategy_id', sa.Uuid(), nullable=True),
    sa.Column('portfolio_id', sa.Uuid(), nullable=True),
    sa.Column('filled_quantity', sa.Numeric(), nullable=True),
    sa.Column('created_at', itrader.storage.types.UtcIsoText(), nullable=True),
    sa.Column('updated_at', itrader.storage.types.UtcIsoText(), nullable=True),
    sa.Column('filled_at', itrader.storage.types.UtcIsoText(), nullable=True),
    sa.Column('cancelled_at', itrader.storage.types.UtcIsoText(), nullable=True),
    sa.Column('expired_at', itrader.storage.types.UtcIsoText(), nullable=True),
    sa.Column('expiry_time', itrader.storage.types.UtcIsoText(), nullable=True),
    sa.Column('parent_order_id', sa.Uuid(), nullable=True),
    sa.Column('rejection_reason', sa.String(), nullable=True),
    sa.Column('modification_count', sa.Integer(), nullable=True),
    sa.Column('last_modification_time', itrader.storage.types.UtcIsoText(), nullable=True),
    sa.Column('leverage', sa.Numeric(), nullable=True),
    sa.Column('trail_type', sa.String(), nullable=True),
    sa.Column('trail_value', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['parent_order_id'], ['orders.id'], name=op.f('fk_orders_parent_order_id_orders'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orders'))
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orders_parent_order_id'), ['parent_order_id'], unique=False)
        batch_op.create_index('ix_orders_portfolio_status', ['portfolio_id', 'status'], unique=False)

    op.create_table('positions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('portfolio_id', sa.Uuid(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('side', sa.String(), nullable=False),
    sa.Column('leverage', sa.Numeric(), nullable=False),
    sa.Column('current_price', sa.Numeric(), nullable=False),
    sa.Column('current_time', itrader.storage.types.UtcIsoText(), nullable=False),
    sa.Column('buy_quantity', sa.Numeric(), nullable=False),
    sa.Column('sell_quantity', sa.Numeric(), nullable=False),
    sa.Column('avg_bought', sa.Numeric(), nullable=False),
    sa.Column('avg_sold', sa.Numeric(), nullable=False),
    sa.Column('buy_commission', sa.Numeric(), nullable=False),
    sa.Column('sell_commission', sa.Numeric(), nullable=False),
    sa.Column('entry_date', itrader.storage.types.UtcIsoText(), nullable=False),
    sa.Column('exit_date', itrader.storage.types.UtcIsoText(), nullable=True),
    sa.Column('_last_accrual_time', itrader.storage.types.UtcIsoText(), nullable=True),
    sa.Column('is_open', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_positions'))
    )
    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.create_index('ix_positions_portfolio_open', ['portfolio_id', 'is_open'], unique=False)

    op.create_table('signals',
    sa.Column('signal_id', sa.Uuid(), nullable=False),
    sa.Column('strategy_id', sa.Uuid(), nullable=True),
    sa.Column('ticker', sa.String(), nullable=True),
    sa.Column('time', itrader.storage.types.UtcIsoText(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('order_type', sa.String(), nullable=True),
    sa.Column('stop_loss', sa.Numeric(), nullable=True),
    sa.Column('take_profit', sa.Numeric(), nullable=True),
    sa.Column('exit_fraction', sa.Numeric(), nullable=True),
    sa.Column('quantity', sa.Numeric(), nullable=True),
    sa.Column('entry_price', sa.Numeric(), nullable=True),
    sa.Column('config', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.PrimaryKeyConstraint('signal_id', name=op.f('pk_signals'))
    )
    with op.batch_alter_table('signals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_signals_strategy_id'), ['strategy_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_signals_ticker'), ['ticker'], unique=False)

    op.create_table('transactions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('portfolio_id', sa.Uuid(), nullable=False),
    sa.Column('fill_id', sa.Uuid(), nullable=False),
    sa.Column('position_id', sa.Uuid(), nullable=True),
    sa.Column('time', itrader.storage.types.UtcIsoText(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('price', sa.Numeric(), nullable=False),
    sa.Column('quantity', sa.Numeric(), nullable=False),
    sa.Column('commission', sa.Numeric(), nullable=False),
    sa.Column('leverage', sa.Numeric(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transactions'))
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_portfolio_id'), ['portfolio_id'], unique=False)

    op.create_table('order_state_changes',
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('from_status', sa.String(), nullable=True),
    sa.Column('to_status', sa.String(), nullable=True),
    sa.Column('timestamp', itrader.storage.types.UtcIsoText(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('triggered_by', sa.String(), nullable=True),
    sa.Column('additional_data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_order_state_changes_order_id_orders')),
    sa.PrimaryKeyConstraint('order_id', 'seq', name=op.f('pk_order_state_changes'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_state_changes')
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_portfolio_id'))

    op.drop_table('transactions')
    with op.batch_alter_table('signals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_signals_ticker'))
        batch_op.drop_index(batch_op.f('ix_signals_strategy_id'))

    op.drop_table('signals')
    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.drop_index('ix_positions_portfolio_open')

    op.drop_table('positions')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index('ix_orders_portfolio_status')
        batch_op.drop_index(batch_op.f('ix_orders_parent_order_id'))

    op.drop_table('orders')
    op.drop_table('locked_margin')
    op.drop_table('equity_snapshots')
    op.drop_table('cash_reservations')
    with op.batch_alter_table('cash_operations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cash_operations_portfolio_id'))

    op.drop_table('cash_operations')
    # ### end Alembic commands ###
