"""portfolio_account_state

Revision ID: 47f2b41f3ffe
Revises: 2cbf0bf6b0b6
Create Date: 2026-06-30 11:52:33.580362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Autogenerate renders the custom time TypeDecorator by its fully-qualified name
# (``itrader.storage.types.UtcIsoText``) but does NOT emit the import — the standard
# custom-type autogenerate gotcha. Added by hand-review so ``alembic upgrade head`` resolves
# the name instead of raising ``NameError`` (Pitfall 5 / D-09 hand-review — identical to the
# ``2cbf0bf6b0b6_operational_baseline.py`` baseline).
import itrader.storage.types

# revision identifiers, used by Alembic.
revision: str = "47f2b41f3ffe"
down_revision: Union[str, Sequence[str], None] = "2cbf0bf6b0b6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolio_account_state',
    sa.Column('portfolio_id', sa.Uuid(), nullable=False),
    sa.Column('cash_balance', sa.Numeric(), nullable=False),
    sa.Column('realized_pnl', sa.Numeric(), nullable=False),
    sa.Column('total_equity', sa.Numeric(), nullable=False),
    sa.Column('peak_equity', sa.Numeric(), nullable=False),
    sa.Column('open_positions_count', sa.Integer(), nullable=False),
    sa.Column('updated_time', itrader.storage.types.UtcIsoText(), nullable=False),
    sa.PrimaryKeyConstraint('portfolio_id', name=op.f('pk_portfolio_account_state'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('portfolio_account_state')
    # ### end Alembic commands ###
