from abc import ABC, abstractmethod

from itrader.events_handler.events import BarEvent, OrderEvent


class AbstractExecutionHandler(ABC):
	"""Abstract base class for the execution layer's event seam (D-21, #39).

	The ExecutionHandler handles the interaction between order events
	generated by the order layer and the FillEvents that actually occur
	in the market. Concrete handlers route orders to exchanges (simulated
	or live) with identical interfaces, so strategies backtest in a very
	similar manner to the live trading engine.

	Events are the ONLY execution output (D-21): both hooks return
	``None`` and communicate every outcome — EXECUTED, REFUSED or
	CANCELLED — exclusively by putting FillEvents onto the global queue.
	"""

	@abstractmethod
	def on_order(self, event: OrderEvent) -> None:
		"""
		Take an OrderEvent and route it for execution, producing
		a FillEvent that gets placed onto the events queue.

		Parameters
		----------
		event : OrderEvent
			The order event to route to the configured exchange.
		"""
		raise NotImplementedError("Should implement on_order()")

	@abstractmethod
	def on_market_data(self, bar: BarEvent) -> None:
		"""
		Drive resting-order matching against a new market-data bar,
		producing FillEvents for any triggered resting orders.

		Parameters
		----------
		bar : BarEvent
			The new market-data bar to match resting orders against.
		"""
		raise NotImplementedError("Should implement on_market_data()")
