import unittest
from datetime import datetime

from itrader.portfolio_handler.transaction import Transaction, TransactionType
from itrader.portfolio_handler.position import Position, PositionSide


class TestPositionMultipleBuy(unittest.TestCase):
	"""
	Test a Position generated by a transaction being processed
	by the portfolio.
	"""

	@classmethod
	def setUpClass(cls):
		"""
		Set up the test data that will be used across all test methods.
		"""
		cls.ticker = 'BTCUSDT'
		cls.strategy_id = 'test_strategy'
		cls.portfolio_id = 'portfolio_id'

	def test_long_position_multiple_buy(self):
		# Open position
		time = datetime.now()
		type = TransactionType.BUY
		price = 42000
		quantity = 1
		commission = 0
		# TODO: use Transaction.new_transaction() or implement an auto generate ID method
		buy_transaction_1 = Transaction(time, type, self.ticker, 
								price, quantity, commission,
								self.portfolio_id, id=1)
		position = Position.open_position(buy_transaction_1)
		# Increase Long position
		time = datetime.now()
		type = TransactionType.BUY
		price = 50000
		quantity = 2
		commission = 0
		buy_transaction_2 = Transaction(time, type, self.ticker, 
								price, quantity, commission,
								self.portfolio_id, id=2)
		position.update_position(buy_transaction_2)

		self.assertIsInstance(position, Position)
		self.assertIsInstance(position.id, int)  # Just check it's an integer
		self.assertEqual(position.ticker, 'BTCUSDT')
		self.assertEqual(position.portfolio_id, 'portfolio_id')

		self.assertEqual(position.is_open, True)
		self.assertEqual(position.side, PositionSide.LONG)
		self.assertEqual(position.buy_quantity, 3)
		self.assertEqual(position.sell_quantity, 0)
		self.assertAlmostEqual(position.avg_bought, 47333.33, delta=0.01)
		self.assertEqual(position.avg_sold, 0)
		self.assertAlmostEqual(position.avg_price, 47333.33, delta=0.01)
		self.assertEqual(position.market_value, 150000)
		self.assertEqual(position.total_bought, 142000)
		self.assertEqual(position.total_sold, 0)
		self.assertAlmostEqual(position.net_total, 8000, delta=0.01)
		self.assertEqual(position.realised_pnl, 0)
		self.assertAlmostEqual(position.unrealised_pnl, 8000, delta=0.01)

if __name__ == "__main__":
	unittest.main()