from ..base import OrderBase
from itrader.events_handler.event import SignalEvent

from itrader import logger

class ComplianceManager():
	"""
	The Compliance class manage the signal event coming from the 
	strategy class.

	It verify that all the entering rules are compliant with the 
	defined conditions. It verifies if a position is already open 
	and if the number of opened positions in a portfolio reached 
	the defined limit
	"""
	def __init__(self, portfolios = {}):
		self.portfolios = portfolios
		logger.info('   COMPLIANCE MANAGER: Default => OK')

	
	def check_compliance(self, signal: SignalEvent):
		"""
		Check if there's already an opened position in the portfolio
		and if the max. number of positions is reached.

		Parameters
		----------
		signal: `Event object`
			The Signal event generated by a strategy
		"""
		portfolio_id = signal.portfolio_id
		max_position = signal.max_positions
		open_positions = self.portfolios[signal.portfolio_id]['open_positions']

		if signal.ticker in list(open_positions.keys()):
			if signal.action == open_positions[portfolio_id][signal.ticker]['action']:
				signal.verified = False
				logger.warning('COMPLIANCE: Position already opened. Order refused')
				return
		elif (self.portfolios[signal.portfolio_id]['n_open_positions'] >= max_position):
			signal.verified = False
			logger.debug('COMPLIANCE: Max. positions reached. Order refused')
			return
		signal.verified = True
		logger.debug('COMPLIANCE: Order validated')
		return
